# Generated by Django 5.2.1 on 2025-05-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('cuisine', models.CharField(max_length=50)),
                ('cost_rating', models.IntegerField()),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
